---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall
        ports:
        - containerPort: 80
        volumeMounts: # Volume must be created along with volumeMount (see next below)
        - name: heimdall-config
          mountPath: /config # Path within the container, like the right side of a docker bind mount -- /tmp/data:/app/data
          subPath: heimdall/config
      volumes: # Defines a volume that uses an existing PVC (defined below)
      - name: heimdall-config
        persistentVolumeClaim:
          claimName: heimdall-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
spec:
  selector:
    app: heimdall
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heimdall-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb